### ISSUE TITLE
 Variablize Server Name

### ISSUE THREAD

**Issue by Adnan029** [clouddrove/terraform-azure-flexible-postgresql#48]
I suggest that we introduce a variable for it to make it more flexible to choose server name. This way, users can customize it according to their requirements, especially if they need to adhere to specific naming conventions, which is currently not possible.

**Comment by d4kverma** [comment]
@Adnan029 Thank you for the suggestion. We'll check into this. 
If you wish to make adjustments based on your suggestions, you are quite welcome.

**Comment by Adnan029** [comment]
@d4kverma Thanks for the response.

I already created PR for the suggested changes but have to revert back. Kindly take look at my PR -(https://github.com/clouddrove/terraform-azure-flexible-postgresql/pull/47)

**Comment by Adnan029** [comment]
@13archit any thing I can help here

**Comment by 13archit** [comment]
Hi @Adnan029 thanks, but our team has already worked on it and PR is ready from their side and it will be merged shortly. For changes you can refer to [PR](https://github.com/clouddrove/terraform-azure-flexible-postgresql/pull/50) linked to this issue.
